# Generated by Django 4.0.6 on 2022-07-30 16:04

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter Your Category Name here.', max_length=30, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter Your Restaurant Name', max_length=30, unique=True, verbose_name='Restaurant Name')),
                ('Address', models.TextField(help_text='Enter Your Restaurant Address.', max_length=100, verbose_name='Restaurant Address')),
                ('description', models.TextField(help_text='Write some description.', max_length='150', verbose_name='Description')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dzag0ldw1/image/upload/v1659178532/gakiweohz9yqelxpbas0.webp', help_text='Upload image of your Restaurant', max_length=255, verbose_name='Image')),
                ('Owner', models.ForeignKey(help_text='Enter your Owner Name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurantowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Write title of your item', max_length=30, unique=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Write some description.', max_length='150', verbose_name='Description')),
                ('price', models.PositiveIntegerField(help_text='Enter Price', verbose_name='Price')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dzag0ldw1/image/upload/v1659178532/gakiweohz9yqelxpbas0.webp', help_text='Upload image of your item', max_length=255, verbose_name='Image')),
                ('order_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Item Order Count')),
                ('category', models.ManyToManyField(help_text='link your item to category', to='maindisplay.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maindisplay.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='RestaurantCategory',
            field=models.ManyToManyField(to='maindisplay.restaurant'),
        ),
    ]
