# Generated by Django 4.0.6 on 2022-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindisplay', '0003_alter_item_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='link your item to category', to='maindisplay.category'),
        ),
    ]
