# Generated by Django 4.0.6 on 2022-08-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindisplay', '0006_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(help_text='Enter Your Category Name here.', max_length=30, unique=True, verbose_name='Category Name'),
        ),
    ]
