# Generated by Django 4.0.6 on 2022-08-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindisplay', '0007_remove_item_photo_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantitem', to='maindisplay.restaurant'),
        ),
    ]
